### ISSUE TITLE
Assets Library custom API key issues

### ISSUE THREAD

**Issue by Eranziel** [ForgeVTT/fvtt-module-forge-vtt#20]
All of the below are issues noted on v1.14.7 of The Forge module running on local Foundry installations.
- [x] Using a custom API key on a local Foundry instance does not allow browsing the associated Assets Library.
  - Add any custom API key.
  - Open the file picker (e.g. for an actor or item image, scene background, or tile)
  - See an error about being unauthorized.
  - Instead, the user should be shown the assets associated with the custom API key.
- [x] Opening a file picker switches to The Forge source if the current file is local.
  - Add any custom API key.
  - Open the file picker (e.g. for an actor or item image, scene background, or tile) for something which currently uses a file in the user's local data.
  - File picker opens on The Forge source.
  - File picker should open on the User Data source in the correct folder for the current file.
- [x] Changing custom API keys can create misleading behaviour and cause users to think the API key is not working.
  - Add a custom API key.
  - Assign an image from the associated Assets Library to an actor, scene, tile, etc...
  - Change the API key to one from a different user, which does not have any assets at the path of the image selected above.
  - Open the file picker for the image above.
  - The file picker picks The Forge source and gives an unauthorized error.
  - The file picker should open the root folder of the new API key.

**Comment by illianne** [comment]
### Validated fixed: 
✅  Using a custom API key on a local Foundry instance does not allow browsing the associated Assets Library
✅  Opening a file picker switches to The Forge source if the current file is local.
✅ Changing custom API keys can create misleading behaviour and cause users to think the API key is not working.
 
### Smoke tested: 
Local foundry: 
* relative URLs to your own assets
* full URLs to your own assets
* assets in custom API keys/shared folders.
* Uploads/local images
* Asset sync

Forge > Foundry game:
- Read/write folders
- Uploading new
- Shared folders
- Custom api keys

Asset Lib
- Shared folders

@Eranziel I got one console error here that i wasn't able to reproduce in my local foundry. Just wanted to call it out. Let me know if i missed any areas with my smoke testing too. 🙏 

<img width="1680" alt="Screenshot 2023-12-01 at 11 34 31 AM" src="https://github.com/ForgeVTT/fvtt-module-forge-vtt/assets/5169836/358fe610-b098-438a-b2bb-3cf4977f22a5">
