### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by qalucaspacheco1** [ForgeVTT/fvtt-module-forge-vtt#39]
This is a Test

Lucas Pacheco created this defect while executing TC-247:
https://app.testiny.io/p/2/testruns/tr/20/tc/247/edit

**Comment by qalucaspacheco1** [comment]
This is not a valid issue, only created to test integration between Testiny and Github

**Comment by rikmarais** [comment]
I'll go ahead and close this issue since it was created as a test
